// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckuzmfrsqnmpdlakkkzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrdXptZnJzcW5tcGRsYWtra3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjgzODgsImV4cCI6MjA2NTgwNDM4OH0.fLojkySYD_cBhBVFNK09NHcHsqvT9CjM7U91eGS_yMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);