// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oysrkmtxyomvgikvepjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95c3JrbXR4eW9tdmdpa3ZlcGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjcyNTAsImV4cCI6MjA2NTgwMzI1MH0.DGoY9uVzfwK--UttlauYJimdbdrGbPQw-C5lSzLM5mU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);